//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Database
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class DataStudent
    {
        public int? StudentId { get; set; }
        public string StudentName { get; set; }
        public string StudentSubject { get; set; }
        public int? StudentAge { get; set; }

        public List<SelectListItem> SubjectList { get; set; }

    }
}
